// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCExJF1guak6-02CnPdl-n4SAtEYpVhpHI',
    appId: '1:964436961783:web:2e1839465269447b2fe6f2',
    messagingSenderId: '964436961783',
    projectId: 'thop-c91cc',
    authDomain: 'thop-c91cc.firebaseapp.com',
    storageBucket: 'thop-c91cc.appspot.com',
    measurementId: 'G-TXGS8CX9YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALalzvxbUFOIHirPiKJ1rGJjUGX4P8GWc',
    appId: '1:964436961783:android:99e72379104f28f72fe6f2',
    messagingSenderId: '964436961783',
    projectId: 'thop-c91cc',
    storageBucket: 'thop-c91cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl4kaXjUldldz6C0yK601pZwRzoFOzxj4',
    appId: '1:964436961783:ios:636c1ec1d7d4a7512fe6f2',
    messagingSenderId: '964436961783',
    projectId: 'thop-c91cc',
    storageBucket: 'thop-c91cc.appspot.com',
    androidClientId: '964436961783-a8o4552jujkr0f5dutcr63o2rkptnh33.apps.googleusercontent.com',
    iosClientId: '964436961783-q88oduf81obuilh3722i38bia4sdmfhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firsttest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl4kaXjUldldz6C0yK601pZwRzoFOzxj4',
    appId: '1:964436961783:ios:5da827c63fcfa3a22fe6f2',
    messagingSenderId: '964436961783',
    projectId: 'thop-c91cc',
    storageBucket: 'thop-c91cc.appspot.com',
    androidClientId: '964436961783-a8o4552jujkr0f5dutcr63o2rkptnh33.apps.googleusercontent.com',
    iosClientId: '964436961783-ir83paf3o3q4cm6g9cq9n4hgmnc9g7cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firsttest.RunnerTests',
  );
}
